// Regenerates src/lib/icons/ph-icons-data.ts from the full @iconify-json/ph
// icon set, keeping only the icons actually referenced in the codebase.
//
// Run after adding/removing a "ph:xxx" icon reference anywhere in src/:
//   node scripts/extract-icons.mjs
//
// Requires devDependencies: @iconify-json/ph, @iconify/utils

import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { getIcons } from "@iconify/utils";

const rootDir = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

// Find every `ph:icon-name` referenced under src/
const grepOutput = execSync(String.raw`grep -rhoE 'ph:[a-z0-9-]+' src`, {
  cwd: rootDir,
  encoding: "utf-8",
});
const iconNames = [...new Set(grepOutput.trim().split("\n"))]
  .map((full) => full.replace(/^ph:/, ""))
  .sort();

const fullSet = JSON.parse(
  fs.readFileSync(path.join(rootDir, "node_modules/@iconify-json/ph/icons.json"), "utf-8")
);

const subset = getIcons(fullSet, iconNames);
if (!subset) {
  throw new Error("Failed to extract icon subset - check icon names in src/");
}

const found = Object.keys(subset.icons).length;
if (found !== iconNames.length) {
  console.warn(`Warning: found ${found} of ${iconNames.length} requested icons`);
}

const outPath = path.join(rootDir, "src/lib/icons/ph-icons-data.ts");
const contents =
  `// AUTO-GENERATED by scripts/extract-icons.mjs - do not edit by hand.\n` +
  `// Subset of Phosphor icons (from @iconify-json/ph) actually used in this app.\n` +
  `import type { IconifyJSON } from "@iconify/types";\n\n` +
  `const phIconsData: IconifyJSON = ${JSON.stringify(subset)};\n\n` +
  `export default phIconsData;\n`;

fs.writeFileSync(outPath, contents);
console.log(`Wrote ${found} icons to ${path.relative(rootDir, outPath)}`);
